USE [master]
GO
-- CREATES THE ACTUAL DATABASE, if needed
CREATE DATABASE [WebApiDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebApiDatabase', FILENAME = N'C:\Db\WebApiDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebApiDatabase_log', FILENAME = N'C:\Db\WebApiDatabase.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebApiDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebApiDatabase] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [WebApiDatabase] SET ANSI_NULLS ON 
GO

ALTER DATABASE [WebApiDatabase] SET ANSI_PADDING ON 
GO

ALTER DATABASE [WebApiDatabase] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [WebApiDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebApiDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebApiDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebApiDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebApiDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebApiDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebApiDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebApiDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebApiDatabase] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [WebApiDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebApiDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WebApiDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebApiDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebApiDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebApiDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebApiDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebApiDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebApiDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebApiDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebApiDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [WebApiDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebApiDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebApiDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebApiDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebApiDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebApiDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WebApiDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WebApiDatabase] SET  READ_WRITE 
GO


